name: Bug report
description: Report a bug you've encountered
labels: ["bug"]
projects: ["veritaware/6"]
type: Bug
assignees:
  - nidrax
body:
  - type: input
    attributes:
    label: Spritefinity version
    description: Paste Spritefinity version between quotes down below. You'll find it in the bottom left corner when you open the software. If you're on a dev version, specify the commit hash
    placeholder: e.g., "v1.2.3" or "abcdefg"
    required: true
    style: long
    id: version
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is
      placeholder: e.g., "When I try to export a sprite sheet, the software crashes"
      required: true
      id: bug-description
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour
      placeholder: e.g., "1. Open Spritefinity\n2. Load a project\n3. Click on Export\n4. See error"
      required: true
      id: steps-to-reproduce
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen
      placeholder: e.g., "The sprite sheet should export without errors"
      required: true
      style: long
      id: expected-behaviour
  - type: input
    attributes:
      label: Operative System
      description: The operative system you're using (e.g., Windows 10, macOS 11.2, Ubuntu 20.04)
      placeholder: e.g., "Windows 10"
      required: false
      id: os
  - type: input
    attributes:
      label: CPU
      description: The CPU model of your computer (e.g., Intel Core i7-9700K, AMD Ryzen 5 3600)
      placeholder: e.g., "Intel Core i7-9700K"
      required: false
      id: cpu
  - type: input
    attributes:
      label: GPU
      description: The GPU model of your computer (e.g., NVIDIA GeForce RTX 2070, AMD Radeon RX 5700 XT). Only needed for graphical issues
      placeholder: e.g., "NVIDIA GeForce RTX 2070"
      required: false
      id: gpu
  - type: textarea
    attributes:
      label: Screenshots
      description: Screenshots or videos to help explain your problem
      placeholder: e.g., "![screenshot](url_to_screenshot)"
      required: false
      style: long
      id: screenshots
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: e.g., "I noticed this issue started happening after I updated to the latest version"
      required: false
      style: long
      id: additional-context