name: Code quality
description: Have you seen bad code? Click here
labels: ["code-ql"]
projects: ["veritaware/6"]
type: Task
body:
  - type: textarea
    attributes:
      label: What's wrong with the code?
      description: A clear and concise description of the poor quality you've noticed
      placeholder: e.g., "The function X has too many parameters and is hard to understand"
      required: true
      id: code-problem
  - type: textarea
    attributes:
      label: How should it be improved?
      description: A clear and concise description of what you think is a better approach
      placeholder: e.g., "Refactor the function to use a configuration object instead of multiple parameters"
      required: true
      id: improvement-suggestion
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the issue here
      placeholder: e.g., "This code is in the file src/app/main.cpp"
      required: false
      style: long
      id: additional-context
