name: Documentation
description: Something wrong with the docs? Tell us here
labels: ["docs"]
projects: ["veritaware/6"]
type: Task
assignees:
  - copilot
body:
  - type: textarea
    attributes:
      label: Documentation issue
      description: Please describe what's wrong with the documentation (please no walls of text :P)
      placeholder: e.g., "The installation guide is missing steps for macOS"
      required: true
      id: documentation-issue
  - type: textarea
    attributes:
      label: Suggested improvement
      description: How do you think the documentation should be improved?
      placeholder: e.g., "Add a section explaining how to install on macOS"
      required: false
      id: suggested-improvement
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the documentation issue here
      placeholder: e.g., "This affected me when trying to set up the project"
      required: false
      style: long
      id: additional-context
