name: Feature request
description: Suggest an idea for this project
labels: ["feature"]
projects: ["veritaware/6"]
type: Feature
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is
      placeholder: e.g., "I'm always frustrated when I have to manually export each layer individually"
      required: true
      id: problem-description
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: e.g., "Add a 'Batch Export Layers' feature that exports all layers at once"
      required: true
      id: solution-description
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: e.g., "I considered using a script, but it would be better to have a built-in feature"
      required: false
      style: long
      id: alternatives
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
      placeholder: e.g., "Other sprite editors like X and Y have this feature"
      required: false
      style: long
      id: additional-context
